### ISSUE TITLE
should JNI header files be generated?

### ISSUE THREAD

**Issue by luxe** [hlopko/bazel-jni-example#3]
https://github.com/hlopko/bazel-jni-example/blob/3f8a937abbae7bd779eae433832c989ebce44183/Main.h#L1

How was this file generated?  I'm not sure if I should write these header files myself or if there is a tool that can generate them.

**Comment by hlopko** [comment]
Honestly, I don't remember. It can very much be that I copied it from some StackOverflow answer and tuned it by hand :/
